name: Hello Github Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello-github-actions:
    runs-on: ubuntu-latest
    
    steps:
    - uses: jjohney/github-actions@v1.0.1
    
